#!/bin/bash
#
# Copyright (C) 2016 Eaton
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#! \file    bios-dmf
#  \brief   Helper script handling DMF files (part of Extreme support)
#  \author  Michal Vyskocil <MichalVyskocil@Eaton.com>
#  \details Helper script for handling DMF files, it can copy and enable things
#

set -e

export PATH=/bin:/usr/bin
export LC_ALL=C
#hack for Makefile.am and make distcheck
export PROG=$(readlink -f "${0}")

die() {
    echo "${@}" >&2
    exit 1
}

TMPDIR=${TMPDIR:-/tmp}
NUTCONFIGDIR=/etc/nut
[ -d "$NUTCONFIGDIR" ] || NUTCONFIGDIR=/etc/ups
[ -d "$NUTCONFIGDIR" ] || die "NUT configuration directory not found"
NUTCONFIG="$NUTCONFIGDIR/ups.conf"

DMFSNMPD=/usr/share/nut/dmfsnmp.d/
DMFSNMP=/usr/share/nut/dmfsnmp/

[ -d "${DMFSNMPD}" ] || die "Can't find NUT DMF runtime dir at ${DMFSNMPD}"

usage () {
    echo "${PROG}"
    echo "upload dmf1 [dmf2 ...] - upload dmf files to ${DMFSNMPD}"
    echo "enable asset 1 [asset2 ...] - enable dmf for particular asset"
    echo "list - list all assets with enabled dmf"
}

do_upload () {
    cp "${@}" -t ${DMFSNMP}
    for dmf in "${@}"; do
        DMFNAME=`basename $dmf`
        ln -s ${DMFSNMP}${DMFNAME} -t ${DMFSNMPD}
    done
}

do_enable () {
    die "implement do_enable ${@}"
}

do_disable () {
    die "implement do_disable ${@}"
}

do_list () {
    die "implement do_list ${@}"
}

COMMAND=${1}
if [[ -z "${COMMAND}" ]]; then
    COMMAND="--help"
else
    shift 1
fi

case "${COMMAND}" in
    "upload")
        do_upload "${@}"
        ;;
    "enable")
        do_enable "${@}"
        ;;
    "disable")
        do_disable "${@}"
        ;;
    "list")
        do_list "${@}"
        ;;
    *)
        usage
        exit 1
        ;;
esac
