#!/bin/bash
#
# Copyright (C) 2014,2016 Eaton
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#! \file    fty-nutconfig
#  \brief   Helper script for autoconfig agent
#  \author  Tomas Halman <TomasHalman@Eaton.com>
#           Michal Vyskocil <MichalVyskocil@Eaton.com>
#  \details Helper script for autoconfig agent. It creates new NUT configuration
#           from files stored in /var/lib/fty/fty-nut/devices.

set -e

export PATH=/bin:/usr/bin
export LC_ALL=C
#hack for Makefile.am and make distcheck
export PROG=$(readlink -f "${0}")

die() {
    echo "${@}" >&2
    exit 1
}

TMPDIR=${TMPDIR:-/tmp}
BIOSCONFDIR=/var/lib/fty/fty-nut/devices
NUTCONFIGDIR=/etc/nut
[ -d "$NUTCONFIGDIR" ] || NUTCONFIGDIR=/etc/ups
[ -d "$NUTCONFIGDIR" ] || die "NUT configuration directory not found"
NUTCONFIG="$NUTCONFIGDIR/ups.conf"

mkdir -p "${BIOSCONFDIR}"
chown -R bios:bios-infra "${BIOSCONFDIR}"

TMPFILE=$(mktemp -p "${TMPDIR}" nutconfig.XXXXXXXXXX)
if cat "${BIOSCONFDIR}"/* 2> /dev/null > "${TMPFILE}"; then
    mv "${TMPFILE}" "$NUTCONFIG"
    chmod 0640 "${NUTCONFIG}"
    chown root:nut "${NUTCONFIG}"
    exit 0
else
    rm "${TMPFILE}" >/dev/null 2>&1
    die "No configuration found"
fi
