#!/bin/bash
#
# Copyright (C) 2014 - 2018 Eaton
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#! \file    fty-nutconfig
#  \brief   Helper script for autoconfig agent
#  \author  Tomas Halman <TomasHalman@Eaton.com>
#           Michal Vyskocil <MichalVyskocil@Eaton.com>
#           Jim Klimov <EvgenyKlimov@Eaton.com>
#  \details Helper script for autoconfig agent. It creates new NUT configuration
#           from files stored in /var/lib/fty/fty-nut/devices.

set -e
shopt -s nullglob

export PATH=/bin:/usr/bin
export LC_ALL=C
#hack for Makefile.am and make distcheck
export PROG=$(readlink -f "${0}")

die() {
    echo "${@}" >&2
    exit 1
}

TMPDIR=${TMPDIR:-/tmp}
BIOSCONFDIR=/var/lib/fty/fty-nut/devices
NUTCONFIGDIR=/etc/nut
[ -d "$NUTCONFIGDIR" ] || NUTCONFIGDIR=/etc/ups
[ -d "$NUTCONFIGDIR" ] || die "NUT configuration directory not found"
NUTCONFIG="$NUTCONFIGDIR/ups.conf"

mkdir -p "${BIOSCONFDIR}"
chown -R bios:bios-infra "${BIOSCONFDIR}"

TMPFILE=$(mktemp -p "${TMPDIR}" nutconfig.XXXXXXXXXX)

cat << EOF > "${TMPFILE}"
# Data-walks of networked devices to initialize a NUT driver state
# can take considerable time; we should allow for that to succeed.
maxstartdelay = 180

EOF
RES=$?

if [ "$RES" = 0 ]; then
    cat "${BIOSCONFDIR}"/* /dev/null 2> /dev/null >> "${TMPFILE}" || RES=$?
fi

if [ "$RES" = 0 ] && [ ! -s /etc/systemd/system/nut-driver@.service.d/timeout.conf ] ; then
    # Use drop-in configuration to override settings of a bundled service file
    mkdir -p /etc/systemd/system/nut-driver@.service.d/
    cat << EOF > /etc/systemd/system/nut-driver@.service.d/timeout.conf
[Service]
# For 42ity: align with "maxstartdelay = 180" in /etc/nut/ups.conf
TimeoutStartSec=190s
EOF
RES=$?
    if [ "$RES" = 0 ] ; then
        chown -R root:root /etc/systemd/system/nut-driver@.service.d/
        /bin/systemctl daemon-reload
    fi
fi

if [ "$RES" = 0 ] ; then
    if diff -q "${NUTCONFIG}" "${TMPFILE}" ; then
        # Avoid wearing out the flash storage by needless updates
        echo "NUT configuration did not change since last generation" >&2

        # Still work towards regularly reducing the chance that we
        # could have missed some NUT config changes earlier (posted
        # while the script was already processing earlier data):
        /bin/systemctl start --no-block nut-driver-enumerator.service || true

        exit 0
    fi

    # This can take a while and needs space; have our moves atomic
    mv -f "${TMPFILE}" "${NUTCONFIG}.tmp" || die "Error moving ups.conf from temporary to final directory"
    mv -f "${NUTCONFIG}.tmp" "${NUTCONFIG}" || die "Error atomically moving ups.conf from temporary to final file"
    chmod 0640 "${NUTCONFIG}"
    chown root:nut "${NUTCONFIG}"
    exit 0
else
    rm "${TMPFILE}" >/dev/null 2>&1
    die "No configuration found"
fi
