/*  =========================================================================
    agent_nut_classes - private header file

    Copyright (C) 2014 - 2015 Eaton                                        
                                                                           
    This program is free software; you can redistribute it and/or modify   
    it under the terms of the GNU General Public License as published by   
    the Free Software Foundation; either version 2 of the License, or      
    (at your option) any later version.                                    
                                                                           
    This program is distributed in the hope that it will be useful,        
    but WITHOUT ANY WARRANTY; without even the implied warranty of         
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          
    GNU General Public License for more details.                           
                                                                           
    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.            
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
    =========================================================================
*/

#ifndef AGENT_NUT_CLASSES_H_INCLUDED
#define AGENT_NUT_CLASSES_H_INCLUDED

//  Platform definitions, must come first
#include "platform.h"

//  External API
#include "../include/agent_nut.h"

//  Internal API
#include "logger.h"
#include "fsutils.h"
#include "actor_commands.h"
#include "ups_status.h"
#include "nut_device.h"
#include "nut_agent.h"
#include "nut_configurator.h"
#include "nutscan.h"
#include "cidr.h"
#include "subprocess.h"

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
AGENT_NUT_EXPORT void
    logger_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
AGENT_NUT_EXPORT void
    fsutils_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
AGENT_NUT_EXPORT void
    actor_commands_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
AGENT_NUT_EXPORT void
    ups_status_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
AGENT_NUT_EXPORT void
    nut_device_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
AGENT_NUT_EXPORT void
    nut_agent_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
AGENT_NUT_EXPORT void
    nut_configurator_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
AGENT_NUT_EXPORT void
    nutscan_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
AGENT_NUT_EXPORT void
    cidr_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
AGENT_NUT_EXPORT void
    subprocess_test (bool verbose);

#endif
